modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"

[[mods]]
modId="lgmarbles"
version="${file.jarVersion}"
displayName="Marbles"
logoFile="examplemod.png"
credits=""
authors="DarkCow, LegondaryGeek"
description='''
Simple mod adding marbles with collision physics
'''

[[dependencies.lgmarbles]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"


[[dependencies.lgmarbles]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
